# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('is_panorama', models.BooleanField(default=False, verbose_name='is-panorama')),
                ('background', models.CharField(blank=True, max_length=32, null=True, verbose_name='background')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='project.Project')),
            ],
        ),
    ]
