# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='gap_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='pan_start_point',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
