# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20161012_0114'),
        ('scene', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='project.Project'),
            preserve_default=False,
        ),
    ]
