# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0002_auto_20170202_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scene',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scene',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
