# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0003_auto_20170224_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='equirectangular_background_image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='scene',
            name='scene_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
