# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPasswordResetEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_template', models.CharField(default='Password reset for very.gd', max_length=64, verbose_name='Subject Template')),
                ('plaintext_template', models.TextField(default='', verbose_name='Plaintext Body Template')),
                ('html_template', models.TextField(default='', verbose_name='HTML Body Template')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'user password reset e-mail settings',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('reset_password_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='very_gd_users.UserPasswordResetEmail')),
            ],
            options={
                'verbose_name_plural': 'user settings',
            },
        ),
        migrations.CreateModel(
            name='UserSignUpEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_template', models.CharField(default='Welcome to very.gd!', max_length=64, verbose_name='Subject Template')),
                ('plaintext_template', models.TextField(default='', verbose_name='Plaintext Body Template')),
                ('html_template', models.TextField(default="\nHi, {{username}}!\nWelcome to very.gd! We're so glad you've joined us. Here are some steps to get you started.\n", verbose_name='HTML Body Template')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'user e-mail settings',
            },
        ),
        migrations.AddField(
            model_name='usersettings',
            name='signup_email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='very_gd_users.UserSignUpEmail'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='sites.Site'),
        ),
    ]
