# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 03:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policy', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='profile photo')),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('accepted_policies', models.ManyToManyField(to='policy.Policy')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='payment.Payment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPasswordResetEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_template', models.CharField(default='Password reset for very.gd', max_length=64, verbose_name='Subject Template')),
                ('plaintext_template', models.TextField(default='', verbose_name='Plaintext Body Template')),
                ('html_template', models.TextField(default='', verbose_name='HTML Body Template')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'user password reset e-mail settings',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('reset_password_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='users.UserPasswordResetEmail')),
            ],
            options={
                'verbose_name_plural': 'user settings',
            },
        ),
        migrations.CreateModel(
            name='UserSignUpEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_template', models.CharField(default='Welcome to media portal!', max_length=64, verbose_name='Subject Template')),
                ('plaintext_template', models.TextField(default='', verbose_name='Plaintext Body Template')),
                ('html_template', models.TextField(default="\nHi, {{username}}!\nWelcome to very.gd! We're so glad you've joined us. Here are some steps to get you started.\n", verbose_name='HTML Body Template')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'user e-mail settings',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='usersettings',
            name='signup_email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='users.UserSignUpEmail'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='site',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_settings', to='sites.Site'),
        ),
    ]
