# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignupemail',
            name='subject_template',
            field=models.CharField(default='Welcome to media portal!', max_length=64, verbose_name='Subject Template'),
        ),
    ]
