# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='total_content_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='file_size_quota_bytes',
            field=models.BigIntegerField(blank=True, default=10000000, null=True),
        ),
    ]
