# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 23:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('very_gd_users', '0002_auto_20161101_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='profile photo')),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('accepted_policies', models.ManyToManyField(to='policy.Policy')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='payment.Payment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='site',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_settings', to='sites.Site'),
        ),
    ]
