# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170119_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumMember',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                    parent_link=True, primary_key=True, serialize=False,
                                                    to='users.Member')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.member',),
        ),
    ]
