# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 02:14
from __future__ import unicode_literals

from django.db import migrations


def create_premium_members(apps, schema_editor):
    PremiumMember = apps.get_model('users', 'PremiumMember')
    Member = apps.get_model('users', 'Member')

    for member in Member.objects.all():
        if member.payment:
            premium_member = PremiumMember(member_ptr=member.pk)
            premium_member.save()


def remove_premium_members(apps, schema_editor):
    PremiumMember = apps.get_model('users', 'PremiumMember')

    for premium_member in PremiumMember.objects.all():
        premium_member.delete(keep_parents=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_premiummember'),
    ]

    operations = [
        migrations.RunPython(create_premium_members, remove_premium_members)
    ]
