# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_premiummember'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFileSizeQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_quota_bytes', models.BigIntegerField(blank=True, default=100000000, null=True)),
                ('premium_quota_bytes', models.BigIntegerField(blank=True, default=1000000000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='file_size_quota_bytes',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='quotas',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='users.UserFileSizeQuota'),
            preserve_default=False,
        ),
    ]
