# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161112_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='total_content_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='file_size_quota_bytes',
            field=models.BigIntegerField(blank=True, default=10000000, null=True),
        ),
    ]
