# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 18:27
from __future__ import unicode_literals

from django.db import migrations, models


def combine_names(apps, schema_editor):
    Member = apps.get_model('users', 'Member')

    for cls in (Member,):
        for person in cls.objects.all():
            person.full_name = '{0} {1}'.format(person.user.first_name, person.user.last_name)
            person.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170124_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='full_name',
            field=models.CharField(default=1, max_length=72),
            preserve_default=False,
        ),
        migrations.RunPython(combine_names, reverse_code=noop),
    ]
