# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import users.auth.group


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('users', '0004_auto_20161115_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
            ],
            options={
                'permissions': (('owner', 'owner of media group'),),
            },
            bases=('auth.group',),
            managers=[
                ('objects', users.auth.group.MediaGroupManager()),
            ],
        ),
    ]
