-   repo: git://github.com/pre-commit/mirrors-scss-lint
    sha: v0.52.0
    hooks:
    -   id: scss-lint
-   repo: git://github.com/pre-commit/mirrors-jshint
    sha: v2.9.4
    hooks:
    -   id: jshint
-   repo: git://github.com/elidupuis/mirrors-jscs
    sha: 92b7f2ab393e9860a3beda0db6da4563d276483b
    hooks:
    -   id: jscs
