# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import media_portal.group.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
            ],
            options={
                'abstract': False,
                'permissions': (('owner', 'owner of media group'),),
            },
            bases=('auth.group',),
            managers=[
                ('objects', media_portal.group.models.AlbumGroupManager()),
            ],
        ),
    ]
