# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel', '0001_initial'),
        ('users', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelvideo',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='project.Project'),
        ),
        migrations.AddField(
            model_name='panelvideo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='users.Member'),
        ),
        migrations.AddField(
            model_name='panelimage',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.Project'),
        ),
        migrations.AddField(
            model_name='panelimage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.Member'),
        ),
    ]
