# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel', '0001_initial'),
        ('scene', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelvideo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='users.Member'),
        ),
        migrations.AddField(
            model_name='panelvideo',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='scene.Scene'),
        ),
        migrations.AddField(
            model_name='panelimage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.Member'),
        ),
        migrations.AddField(
            model_name='panelimage',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scene.Scene'),
        ),
    ]
