# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20160930_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelimage',
            name='related_tag',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='panelimage',
            name='tag',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='panelvideo',
            name='related_tag',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='panelvideo',
            name='tag',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
