# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0001_initial'),
        ('panel', '0004_auto_20161004_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelimage',
            name='album',
        ),
        migrations.RemoveField(
            model_name='panelimage',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='panelvideo',
            name='album',
        ),
        migrations.RemoveField(
            model_name='panelvideo',
            name='tag',
        ),
        migrations.AddField(
            model_name='panelimage',
            name='scene',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scene.Scene'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panelvideo',
            name='scene',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='scene.Scene'),
            preserve_default=False,
        ),
    ]
