# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelimage',
            name='is_panorama',
        ),
        migrations.RemoveField(
            model_name='panelvideo',
            name='is_panorama',
        ),
    ]
