# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_auto_20161018_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelimage',
            name='hotspots',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='panelvideo',
            name='hotspots',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='panelimage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='very_gd_users.Member'),
        ),
        migrations.AlterField(
            model_name='panelvideo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='very_gd_users.Member'),
        ),
    ]
