# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_uuid', models.CharField(default=project.models.get_default_shortuuid, editable=False, max_length=22, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
    ]
