# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_background_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='decade',
        ),
    ]
