# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20170121_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
