# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20161012_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='background_color',
        ),
    ]
