# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20170322_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
