# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_project_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_uuid',
            field=models.CharField(default=1, editable=False, max_length=22),
            preserve_default=False,
        ),
    ]
