# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 23:19
from __future__ import unicode_literals

import shortuuid

from django.db import migrations


def add_short_uuid(apps, schema_editor):
    Project = apps.get_model('project', 'Project')

    for project in Project.objects.all():
        project.short_uuid = shortuuid.uuid()
        project.save()


def remove_short_uuid(apps, schema_editor):
    Project = apps.get_model('project', 'Project')

    for project in Project.objects.all():
        project.short_uuid = None
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_short_uuid'),
    ]

    operations = [
        migrations.RunPython(add_short_uuid, remove_short_uuid),
    ]
