# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20161028_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_uuid',
            field=models.CharField(default=project.models.get_default_shortuuid, editable=False, max_length=22, unique=True),
        ),
    ]
